theme: minima
title: Zero Reservations
author: John Duan
description: Here I'll be posting about my research into Deep Learning and it's applications. Also to serve as a place for my thoughts about life and the world. I hope to reach an audience of like-minded people. 
